---
name: test semver 

on:
  push:
    paths:
      - action.yaml
    branches:
      - "*"

jobs:
  main:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get latest version
        id: lv
        run: |
          echo "latest-version=v0.5.0" >> $GITHUB_OUTPUT

      - name: Calculate version
        id: semver
        uses: ck3mp3r/semver-version-action@develop
        with:
          current-version: ${{ steps.lv.outputs.latest-version }}   

      - name: Print new version
        run: |
          echo "New version: ${{ steps.semver.outputs.semver }}"
